# Generated by Django 4.1.5 on 2023-03-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leetcode_details',
            new_name='leetcode_acc',
        ),
    ]
