# Generated by Django 4.1.5 on 2023-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leetcode_acc_last_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcode_acc',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
