# Generated by Django 4.1.5 on 2023-04-04 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_leetcode_acc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcode_acc',
            name='last_solved',
            field=models.CharField(blank=True, default='Scraping..', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leetcode_acc',
            name='photo_url',
            field=models.CharField(blank=True, default='Scarping..', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leetcode_acc',
            name='rank',
            field=models.CharField(blank=True, default='Scraping..', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='codechef_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='Scraping..', max_length=100, null=True)),
                ('global_rank', models.CharField(blank=True, default='Scraping..', max_length=10, null=True)),
                ('country_rank', models.CharField(blank=True, default='Scraping..', max_length=10, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('stars', models.IntegerField(blank=True, default=0, null=True)),
                ('photo_url', models.CharField(blank=True, default='Scarping..', max_length=100, null=True)),
                ('number_of_questions', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
