# Generated by Django 4.1.5 on 2023-04-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leetcode_acc_last_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechef_acc',
            name='stars',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
