# Generated by Django 4.1.5 on 2023-04-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_codechef_acc_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leetcode_name',
        ),
    ]
